CREATE TABLE CATALOGUE (
     ID         SERIAL PRIMARY KEY,
     REF	    VARCHAR(50),
     TITRE	    VARCHAR(255),
     PRIX	    FLOAT
);
INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A1','voiture',10000);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A2','smartphone',500);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A3','verre',3);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A4','essence',100);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A5','yaourt',3);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A6','alcool',15);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A7','guitare',100);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A8','livres',20);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A9','habits',15);

INSERT INTO CATALOGUE (REF,TITRE,PRIX) VALUES ( 'A10','bouteille de vin',20);